version: '2'

volumes:
  build:
    driver: local

services:
  test:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile
      args:
        ssh_prv_key: ${GITHUB_SSH_PRIV}
        ssh_pub_key: ${GITHUB_SSH_PUB}
        git_author_email: ${GIT_AUTHOR_EMAIL}
        git_author_name: ${GIT_AUTHOR_NAME}
    volumes:
      - build:/flair-notifications/node_modules
    command: ["npm", "test"]
  release:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile
      args:
        ssh_prv_key: ${GITHUB_SSH_PRIV}
        ssh_pub_key: ${GITHUB_SSH_PUB}
    volumes:
      - build:/flair-notifications/node_modules
    command: ["npm", "run", "release", "--", "patch", "--ci"]