version: '2'

volumes:
  build:
    driver: local

services:
  base:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile
      args:
        token: ${GIT_TOKEN}
        git_author_email: ${GIT_AUTHOR_EMAIL}
        git_author_name: ${GIT_AUTHOR_NAME}
    image: flair-notification

  test:
    image: flair-notification
    links:
      - db:flair-notifications-pgsql
    environment:
      NODE_ENV: "production"
    command: ["npm", "test"]
  release:
    image: flair-notification
    command: ["npm", "run", "release", "--", "patch", "--ci"]

  db:
    image: postgres:9.4-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "nodeDB"

  agent:
    image: jmenga/ansible
    links:
      - db
    environment:
      PROBE_HOST: "db"
      PROBE_PORT: "5432"
    command: ["probe.yml"]