httpPort: 8090
grpcPort: 8091
imageFolder: ./images/
grpcEndPoint: localhost:6565
FlairBiEndPoint: http://localhost:8002
mode: grpc
eurekaUrl: http://admin:admin@localhost:8761/eureka
discovery:
  hostname: localhost
  ip: 127.0.0.1
ssl:
  enabled: false
  caCert: certs/trustCertCollectionFile.crt
  serverCert: certs/certChainFile.crt
  serverKey: certs/privateKeyFile.key
mailService:
    host: smtp.ethereal.email
    port: 587
    sender: admin-vizcentric@gmail.com
    testUser: admin@vizcentric.com
    auth :
      user: rudolph.schoen@ethereal.email
      pass: 
