httpPort: 8090
grpcPort: 8091
imageFolder: ./images/
discovery:
  eureka:
    url: http://admin:admin@localhost:8761/eureka
ssl:
  enabled: false
  caCert: certs/trustCertCollectionFile.crt
  serverCert: certs/certChainFile.crt
  serverKey: certs/privateKeyFile.key
mailService:
    host: smtp.sendgrid.net
    port: 587
    sender: chandni.wa@gmail.com
    testUser: admin@vizcentric.com
    auth :
      user: apikey
      pass: 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