port: 8080
imageFolder: /flair-notifications/images/
grpcEndPoint: devsupport-vizcentric.com:6565
mailService:
    serive: gmail
    sender: admin-vizcentric@gmail.com
    testUser: admin@vizcentric.com
    auth :
      user: vizcentric.smpt@gmail.com
      pass:
